" set the runtime path to include Vundle and initialize
set nocompatible              " be iMproved, required
filetype off                  " required

call plug#begin('~/.vim/plugged')

" let Vundle manage Vundle, required
Plug 'VundleVim/Vundle.vim'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-speeddating'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'bling/vim-airline'
Plug 'edkolev/promptline.vim'
" Plug 'bagrat/vim-workspace'
"Plug 'Zuckonit/vim-airline-todo'
Plug 'tpope/vim-fugitive'
Plug 'christoomey/vim-conflicted'
Plug 'scrooloose/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'easymotion/vim-easymotion'
Plug 'chaoren/vim-wordmotion'
Plug 'ervandew/supertab'
Plug 'airblade/vim-gitgutter'
Plug 'xolox/vim-misc'
Plug 'junegunn/vim-easy-align'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-sensible'
Plug 'sjl/gundo.vim'
Plug 'mileszs/ack.vim'
Plug 'ciaranm/detectindent'
" Plug 'scrooloose/syntastic'
Plug 'flazz/vim-colorschemes'
Plug 'Shougo/unite.vim'
Plug 'tpope/vim-commentary'
" Plug 'zef/vim-cycle'
Plug 'dkprice/vim-easygrep'
"Plug 'vim-scripts/vim-colorscheme-switcher'
Plug 'vim-scripts/bufexplorer.zip'
Plug 'tomtom/tlib_vim'
Plug 'MarcWeber/vim-addon-mw-utils'
Plug 'terryma/vim-expand-region'
Plug 'terryma/vim-multiple-cursors'
Plug 'mhinz/vim-startify'
Plug 'nathanaelkane/vim-indent-guides'
Plug 'mhinz/vim-startify'
"Plug 'jceb/vim-orgmode'
Plug 'pbrisbin/vim-mkdir'
Plug 'vim-scripts/mru.vim'
Plug 'junegunn/fzf'
Plug 'mhinz/vim-grepper'
Plug 'Shougo/vimshell.vim'
Plug 'tpope/vim-abolish'
Plug 'haya14busa/incsearch.vim'
Plug 'haya14busa/incsearch-fuzzy.vim'
Plug 'haya14busa/incsearch-easymotion.vim'
" Syntax and lang specific
Plug 'davidhalter/jedi-vim'
Plug 'andrewradev/switch.vim'
Plug 'elzr/vim-json'
Plug 'vim-scripts/bash-support.vim'
Plug 'stephpy/vim-yaml'
Plug 'chase/vim-ansible-yaml'
Plug 'fatih/vim-go'
Plug 'jnwhiteh/vim-golang'
Plug 'vim-scripts/YankRing.vim'
Plug 'lilydjwg/colorizer'
Plug 'raimondi/delimitmate'
Plug 'Yggdroot/indentLine'
Plug 'garbas/vim-snipmate'
Plug 'honza/vim-snippets'
Plug 'SirVer/ultisnips'
Plug 'xolox/vim-easytags'
Plug 'majutsushi/tagbar'
Plug 'tpope/vim-markdown'
Plug 'vimoutliner/vimoutliner'
Plug 'Shougo/vimproc.vim'
Plug 'godlygeek/tabular'
"Themes
Plug 'tyrannicaltoucan/vim-quantum'
Plug 'tomasr/molokai'
Plug 'NLKNguyen/papercolor-theme'
Plug 'roosta/srcery'
Plug 'goatslacker/mango.vim'
"Plug 'romainl/Apprentice'
Plug 'vim-airline/vim-airline-themes'
Plug 'nanotech/jellybeans.vim'
Plug 'altercation/vim-colors-solarized'
Plug 'ryanoasis/vim-devicons'
Plug 'Quramy/tsuquyomi'
Plug 'leafgarland/typescript-vim'
Plug 'jason0x43/vim-js-indent'
Plug 'HerringtonDarkholme/yats.vim'
" YouCompleteMe requires fair bit of compilation so to be done seperately only when required
Plug 'Valloric/YouCompleteMe'
Plug 'pangloss/vim-javascript'
Plug 'mxw/vim-jsx'
Plug 'ianks/vim-tsx'
Plug 'palantir/tslint'
Plug 'w0rp/ale'
Plug 'Chiel92/vim-autoformat'
Plug 'cakebaker/scss-syntax.vim'
Plug 'hail2u/vim-css3-syntax'
Plug 'heavenshell/vim-jsdoc'
Plug 'yssl/QFEnter'
Plug 'Shougo/unite-outline'
Plug 'junegunn/seoul256.vim'
Plug 'AndrewRadev/splitjoin.vim'
Plug 'octol/vim-cpp-enhanced-highlight'
" All of your Plugs must be added before the following line

call plug#end()

filetype plugin indent on    " required


"Bundle 'powerline/powerline', {'rtp': 'powerline/bindings/vim/'}


" include rest of the rc files
source ~/.vim/rcs/basic.vim
source ~/.vim/rcs/filetypes.vim
source ~/.vim/rcs/plugins_config.vim
source ~/.vim/rcs/extended.vim
source ~/.vim/rcs/mappings.vim
source ~/.vim/rcs/skl.vim


:set completeopt=longest,menu,preview
:set diffopt+=vertical

hi Normal guibg=NONE ctermbg=NONE
" :autocmd VimResized * wincmd =
"
au BufRead,BufNewFile *.scss set filetype=scss.css
